# Install Docker and docker-compose
# Build: docker-compose build
# Run:   TESTS=WwwProxy docker-compose up
# Run:   TESTS=TestWwwProxy docker-compose up
# Run:   TESTS="TestWwwProxy WwwProxy" docker-compose up
version: '3'
services:
  runner:
    build: .
    environment:
      NAME:  ${NAME}
      NREP:  ${NREP:-1}
      TESTS: ${TESTS:-WwwProxy}
      WAIT:  ${WAIT:-1}
    volumes:
      - .:/sim
      - ./results:/sim/results
    command: run.sh
